/*
 * Pagamento API
 * Descricao da API de pagamento
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Pagamento;
import io.swagger.client.model.Transacao;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * | O Pagamentos delete endpoint *busca o* pagamento.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void buscaPagamentoTest() throws ApiException {
        Integer id = null;
        Pagamento response = api.buscaPagamento(id);

        // TODO: test validations
    }
    
    /**
     * Cancela um pagamento
     *
     * | O Pagamentos delete endpoint *cancela o* pagamento.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelarPagamentoTest() throws ApiException {
        Integer id = null;
        Pagamento response = api.cancelarPagamento(id);

        // TODO: test validations
    }
    
    /**
     * Confirma o pagamento
     *
     * | O Pagamentos put endpoint *confirma o* pagamento.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void confirmarPagamentoTest() throws ApiException {
        Integer id = null;
        Pagamento response = api.confirmarPagamento(id);

        // TODO: test validations
    }
    
    /**
     * Cria novo pagamento
     *
     * Endpoint de pagamento
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void criarPagamentoTest() throws ApiException {
        Transacao transacao = null;
        Pagamento response = api.criarPagamento(transacao);

        // TODO: test validations
    }
    
}
